project: generic-amd64
configs:
  arch: amd64
  swap: off
  swapsize: 0
  bootsize: 512
  rootfssize: -1
  release: 18
  partition-type: gpt
  bootloader: grub
recovery:
  type: factory_install
  installerfslabel: INSTALLER
  recoverysize: 768
  filesystem-label: ESP
  oem-preinst-hook-dir: OEM_pre_install_hook
  oem-postinst-hook-dir: OEM_post_install_hook
  oem-prereboot-hook-dir: OEM_pre_reboot_hook
  oemlogdir: MFGMEDIA
  restore-confirm-prehook-file: restore_confirm/prehook.sh
  restore-confirm-posthook-file: restore_confirm/posthook.sh
  restore-confirm-timeout: 30
